name: Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    name: cargo fmt

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --check

  python:
    runs-on: ubuntu-latest
    name: ruff

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv tool run ruff check --ignore F403,F405 .
      - run: uv tool run ruff format --check
